'use strict';
let reviewDraftId=null, reviewFragranceId=null, reviewGeneration=0;
function lockReview(locked){reviewForm.querySelectorAll('input,select,textarea').forEach(input=>input.disabled=locked);}
const reviewDialog=document.getElementById('review-dialog'),reviewForm=document.getElementById('review-form');
const experienceNames={own:'Owns it — self-declared',sampled:'Sampled — self-declared',store:'Tested in store — self-declared'};
const disclosureNames={purchased:'Purchased personally / no compensation',gifted:'Gifted bottle or sample',sponsored:'Paid or sponsored',other:'Other disclosure — see review'};
function openReview(r){reviewGeneration++;lockReview(false);reviewForm.reset();reviewDraftId=crypto.randomUUID();reviewFragranceId=r.id;document.getElementById('review-fragrance').textContent=r.name+' · '+r.house;document.getElementById('review-status').textContent='';document.getElementById('review-receipt').hidden=true;document.getElementById('send-review').disabled=false;reviewDialog.showModal();}
document.getElementById('close-review').onclick=()=>reviewDialog.close();
document.getElementById('review-receipt').onclick=()=>reviewDialog.close();
reviewForm.onsubmit=async e=>{
 e.preventDefault();const generation=reviewGeneration;const button=document.getElementById('send-review'),status=document.getElementById('review-status');button.disabled=true;status.textContent='Saving your submission…';
 const form=new FormData(reviewForm),payload={id:reviewDraftId,fragranceId:reviewFragranceId,author:form.get('author'),rating:Number(form.get('rating')),experience:form.get('experience'),disclosure:form.get('disclosure'),body:form.get('body'),consent:form.get('consent')==='on'};lockReview(true);
 try{const response=await fetch('/api/reviews',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const result=await response.json();if(generation!==reviewGeneration)return;if(!response.ok||!result.saved)throw new Error(result.error||'Saving could not be confirmed.');status.textContent='Saved. Your review is pending moderation and is not published. Reference: '+result.id;document.getElementById('review-receipt').hidden=false;}
 catch(error){if(generation!==reviewGeneration)return;status.textContent=error.message+' Your draft remains here.';button.disabled=false;lockReview(false);}
};
async function renderSubmissions(){
 main.innerHTML='<section class="intro"><div><span class="eyebrow">YOUR CONTRIBUTIONS</span><h1>My submissions.</h1><p>Stored with your signed-in account. Pending reviews remain private and do not contribute to community ratings.</p></div></section><div id="submission-results" role="status">Loading your submissions…</div>';
 const container=document.getElementById('submission-results');
 try{const response=await fetch('/api/my-reviews');const result=await response.json();if(!response.ok)throw new Error(result.error||'Submissions could not be loaded.');if(!container.isConnected)return;
 if(!result.reviews.length){container.innerHTML='<div class="emptylist"><h2>No submissions yet.</h2><p>Open a fragrance and choose "Write a review" to contribute your own experience.</p><a class="button" href="#library">Browse fragrances</a></div>';return;}
 container.innerHTML=result.reviews.map(r=>{const fragrance=records.find(f=>f.id===r.fragrance_id);return `<article class="submission-card"><div class="submission-heading"><div><span class="eyebrow">${esc(r.status)} · ${esc(r.created_at.slice(0,10))}</span><h2><a href="#fragrance/${esc(r.fragrance_id)}">${esc(fragrance?.name||'Fragrance')}</a></h2></div><span class="personal-rating">${esc(r.rating)} / 10<small>Your unpublished rating</small></span></div><p class="small">${esc(r.author)} · ${esc(experienceNames[r.experience]||r.experience)}</p><p class="review-body">${esc(r.body)}</p><p class="small">Disclosure: ${esc(disclosureNames[r.disclosure]||r.disclosure)}</p>${r.status==='pending'?`<button class="button secondary" data-withdraw="${esc(r.id)}">Withdraw submission</button>`:''}<p class="small" role="status" data-withdraw-status="${esc(r.id)}"></p></article>`;}).join('');
 container.querySelectorAll('[data-withdraw]').forEach(button=>button.onclick=async()=>{if(!confirm('Withdraw this pending review? This removes it from your submissions.'))return;button.disabled=true;const status=container.querySelector(`[data-withdraw-status="${button.dataset.withdraw}"]`);try{const response=await fetch('/api/reviews/'+encodeURIComponent(button.dataset.withdraw),{method:'DELETE'});const result=await response.json();if(!response.ok)throw new Error(result.error||'Could not withdraw review.');if(location.hash==='#submissions')renderSubmissions();}catch(error){status.textContent=error.message;button.disabled=false;}});
 }catch(error){if(container.isConnected){container.textContent=error.message+' ';const retry=document.createElement('button');retry.className='button secondary';retry.textContent='Retry';retry.onclick=renderSubmissions;container.append(retry);}}
}
